### ISSUE TITLE
Keep connecting to mongo even after 30 seconds.

### ISSUE THREAD

**Issue by axelpale** [axelpale/tresdb#53]

**Comment by axelpale** [comment]
Shutting down mongo yields the following error message:

    { MongoError: failed to reconnect after 30 attempts with interval 1000 ms
    at Connection.<anonymous> (/Users/xeli/Build/tresdb/node_modules/mongodb-core/lib/connection/pool.js:306:15)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:192:7)
    at Socket.<anonymous> (/Users/xeli/Build/tresdb/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:291:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at emitErrorNT (net.js:1280:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    name: 'MongoError',
    message: 'failed to reconnect after 30 attempts with interval 1000 ms' }

When mongo is restarted, a requests to app server outputs the following:

    { MongoError: Topology was destroyed
    at nextFunction (/Users/xeli/Build/tresdb/node_modules/mongodb-core/lib/cursor.js:540:25)
    at AggregationCursor.Cursor.next [as _next] (/Users/xeli/Build/tresdb/node_modules/mongodb-core/lib/cursor.js:692:3)
    at fetchDocs (/Users/xeli/Build/tresdb/node_modules/mongodb/lib/cursor.js:848:10)
    at toArray (/Users/xeli/Build/tresdb/node_modules/mongodb/lib/cursor.js:875:3)
    at AggregationCursor.Cursor.toArray (/Users/xeli/Build/tresdb/node_modules/mongodb/lib/cursor.js:828:44)
    at Object.exports.getWithin (/Users/xeli/Build/tresdb/server/api/markers/dal.js:133:6)
    at exports.getWithin (/Users/xeli/Build/tresdb/server/api/markers/handlers.js:109:7)
    at Layer.handle [as handle_request] (/Users/xeli/Build/tresdb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/xeli/Build/tresdb/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/xeli/Build/tresdb/node_modules/express/lib/router/route.js:112:3) name: 'MongoError', message: 'Topology was destroyed' }
